USER_NOT_FOUND = "Пользователь с именем {username} не найден"
USERNAME_ALREADY_EXIST = "Пользователь с именем {username} уже существует"
NO_MESSAGES = "Вам пока никто не написал"
NO_SENDED_MESSAGES = "Вы пока никому не написали"
USERS_NOT_FOUND = "Пользователи с заданными парметрами не найдены"
