"""updating models

Revision ID: 0fbb92e18986
Revises: b25f4808f579
Create Date: 2023-07-18 15:19:02.931395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fbb92e18986"
down_revision = "b25f4808f579"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
