"""7_change_room_model

Revision ID: 3c75eb8915ca
Revises: 592597d33cea
Create Date: 2023-07-23 11:35:27.053311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c75eb8915ca"
down_revision = "592597d33cea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("author_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "message", "user", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_column("message", "author_id")
    # ### end Alembic commands ###
