"""6_change_room_model

Revision ID: 592597d33cea
Revises: 99834f9b59a1
Create Date: 2023-07-23 10:31:14.618056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "592597d33cea"
down_revision = "99834f9b59a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
