"""5_add_room_model

Revision ID: 99834f9b59a1
Revises: 5cd2ba17e9ef
Create Date: 2023-07-23 10:28:29.174803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99834f9b59a1"
down_revision = "5cd2ba17e9ef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("message", sa.Column("room_id", sa.Integer(), nullable=True))
    op.drop_constraint("message_receiver_id_fkey", "message", type_="foreignkey")
    op.drop_constraint("message_author_id_fkey", "message", type_="foreignkey")
    op.create_foreign_key(None, "message", "room", ["room_id"], ["id"])
    op.drop_column("message", "receiver_id")
    op.drop_column("message", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "message",
        sa.Column("receiver_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_author_id_fkey", "message", "user", ["author_id"], ["id"]
    )
    op.create_foreign_key(
        "message_receiver_id_fkey", "message", "user", ["receiver_id"], ["id"]
    )
    op.drop_column("message", "room_id")
    op.drop_table("room")
    # ### end Alembic commands ###
